export const projectsData = [
  {
    id: 1,
    number: "01",
    title: "강원도청",
    category: "CLONE CODING",
    image: "/img/gwd.png",
    description: "관공서 클론코딩, HTML, CSS",
    url: "https://deldeldep.github.io/gwd/", 
  },
  {
    id: 2,
    number: "02",
    title: "DESIGN HOTELS",
    category: "CLONE CODING",
    image: "/img/hotels.png",
    description: "클론코딩, HTML, SCSS, API",
    url: "https://deldeldep.github.io/hotels/", 
  },
  {
    id: 3,
    number: "03",
    title: "RECIPE",
    category: "Web Development",
    image: "/img/cook.png",
    description: "API, SCSS, REACT",
    url: "https://cook-eta-lilac.vercel.app/",  
  },
  {
    id: 4,
    number: "04",
    title: "TMDB",
    category: "Web Development",
    image: "/img/tmdb.png",
    description: "API, SCSS, REACT",
    url: "https://deldeldep.github.io/tmdbMo1/",  
  },
  {
    id: 5,
    number: "05",
    title: "MY TRIP",
    category: "Web Development",
    image: "/img/mytrip.png",
    description: "API, CRUD, REACT, AI, FIREBASE",
    url: "https://mytrip-89aa2.web.app/", 
  },
  {
    id: 6,
    number: "06",
    title: "BLUEBOTTLE",
    category: "CLONE CODING",
    image: "/img/bluebottle.png",
    description: "클론코딩, API, CRUD, REACT, AI",
    url: "https://deldeldep.github.io/gptbluebottle/", 
  },
  {
    id: 7,
    number: "07",
    title: "NINETREEHOTELS",
    category: "CLONE CODING",
    image: "/img/ninetreehotels.png",
    description: "클론코딩, 반응형, API, CRUD, REACT, AI",
    url: "https://ninetreehotels.vercel.app/", 
  },
  {
    id: 8,
    number: "08",
    title: "NEWS SITE",
    category: "Web Development",
    image: "/img/news.png",
    description: "반응형, API, REACT, AI",
    url: "https://news-coral-six.vercel.app/", 
  },
  {
    id: 9,
    number: "09",
    title: "TEAM PROJECT01",
    category: "Brand Identity",
    image: "/img/moodscape.png",
    description: "팀프로젝트, 기획, 반응형, API, REACT, VERCEL",
    url: "https://mood-scape-umber.vercel.app/", 
  },
  {
    id: 10,
    number: "10",
    title: "TEAM PROJECT02",
    category: "Brand Identity",
    image: "/img/eclat.png",
    description: "팀프로젝트, 기획, REACT, VERCEL",
    url: "https://eclat-t.vercel.app/", 
  },
];